
import javax.swing.JOptionPane;
import DBConnect.Connect;
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tflogin1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pflogin1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        loginb1 = new javax.swing.JButton();
        closeb1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 165, -1));

        tflogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tflogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(tflogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 250, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        pflogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pflogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pflogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(pflogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 250, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        loginb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        loginb1.setText("Login");
        loginb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginb1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 138, 43));

        closeb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        closeb1.setText("Close");
        closeb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeb1ActionPerformed(evt);
            }
        });
        getContentPane().add(closeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login background.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeb1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit application?", "select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
    }//GEN-LAST:event_closeb1ActionPerformed
    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            pflogin1.setEchoChar((char)0);
        }
        else
            pflogin1.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loginb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginb1ActionPerformed

         if(tflogin1.getText().equals("hostel") && pflogin1.getText().equals("admin"))
         {     
             Connect con = new Connect();
             con.db();
             setVisible(false);
             new HomePage().setVisible(true);
         }
         else
             JOptionPane.showMessageDialog(null,"incorrect username or password");
                     
    }//GEN-LAST:event_loginb1ActionPerformed

    private void tflogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflogin1ActionPerformed

    private void pflogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pflogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pflogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeb1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginb1;
    private javax.swing.JPasswordField pflogin1;
    private javax.swing.JTextField tflogin1;
    // End of variables declaration//GEN-END:variables
}
